### ISSUE TITLE
Automatiser - Rajouter les dossiers : cakey et serverkeys

### ISSUE THREAD

**Issue by Boleyno** [kevinchevreuil/CApen-SSL#2]
Bonjour ! 

J'ai ces deux messages lors de l'execution des scripts : 
"Can't open "serverkeys/NAME.key" for writing, No such file or directory"
"Can't open "cakey/NAME.key" for writing, No such file or directory"

J'ai donc créé a la main ces deux dossier dans CApen-SSL.
Cordialement

**Comment by kevinchevreuil** [comment]
Bonjour, ça a été ajouté.

Merci pour le retour :)
